export const LIST_SEARCH_PARAM_KEY = 'keyword'
export const LIST_PAGE_PARAM_KEY = 'page'
export const LIST_PAGE_SIZE_PARAM_KEY = 'pageSize'
export const EMAIL_CODE_DURATION = 60
export const DEFAULT_QUESTION_DATA = { list: [], total: 0 }
export const TRUE_NUMBER = 1
export const FALSE_NUMBER = 0
export const DEFAULT_LIST_PAGE_SIZE = 10
export const DEFAULT_STAT_PAGE_SIZE = 10
